<center>
<h1>เฉลยแบบฝึกหัด week 2</h1>
</center>

### 7. จงหารากของพหุนามต่อไปนี้

<img src="./images/problem10.png" />

### 1.  จากเมทริกซ์ที่กำหนดให้

$$A=\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16 \\
\end{bmatrix}$$

##### 1.1 จงสร้างเมทริกซ์ A ใน Matlab ด้วย 3 วิธีต่อไปนี้
a. พิมพ์ตัวเลข 16 ตัวโดยตรงในเมทริกซ์ <br>
b. ใช้ตัวดำเนินการ colon ในแต่ละแถวของเมทริกซ์ <br>
c. ใช้ตัวดำเนินการ colon ในแต่ละคอลัมน์โดยใช้เครื่องหมาย transpose ร่วมด้วย

In [13]:
# a)
A1 = [ 1 2 3 4; 5 6 7 8; 9 10 11 12; 13 14 15 16]
# b)
A2 = [1:4; 5:8; 9:12; 13:16]
# c)
A3 = [1:4:13; 2:4:14; 3:4:15; 4:4:16]'

A1 =

    1    2    3    4
    5    6    7    8
    9   10   11   12
   13   14   15   16

A2 =

    1    2    3    4
    5    6    7    8
    9   10   11   12
   13   14   15   16

A3 =

    1    2    3    4
    5    6    7    8
    9   10   11   12
   13   14   15   16



##### 1.2 คูณแถวที่ 2 ของเมทริกซ์ A ด้วย $\frac{-9}{5}$ แล้วบวกแถวที่ 3 จากนั้นนำผลลัพท์กลับไปใสในแถวที่ 2


In [14]:
A1(2,:) = (-9/5)*A1(2,:) + A1(3,:)

A1 =

    1.00000    2.00000    3.00000    4.00000
    0.00000   -0.80000   -1.60000   -2.40000
    9.00000   10.00000   11.00000   12.00000
   13.00000   14.00000   15.00000   16.00000



### 2. สร้างเมทริกซ์สามเหลี่ยมขนาด 6x6 ดังนี้

$$A=\begin{bmatrix}
4 & -1 & 0 & \dots & 0 \\
-1 & 4 & -1 \\
 & \ddots & \ddots & \ddots \\
 & & -1 & 4 & -1\\
 0 & \dots & 0 & -1 & 4\\
\end{bmatrix}_{6x6}$$

In [15]:
tri_m = 4*eye(6,6);
v = [-1 -1 -1 -1 -1];
other_diag = diag(v, 1) + diag(v, -1);
tri_m += other_diag

tri_m =

   4  -1   0   0   0   0
  -1   4  -1   0   0   0
   0  -1   4  -1   0   0
   0   0  -1   4  -1   0
   0   0   0  -1   4  -1
   0   0   0   0  -1   4



### 3. สร้างคอลัมน์เวกเตอร์
$$x=\begin{bmatrix} 0 & 1 & 4 & 9 & 16 & \dots & 841 & 900\end{bmatrix}^T$$

In [16]:
x = [0:30].^2;
x'

ans =

     0
     1
     4
     9
    16
    25
    36
    49
    64
    81
   100
   121
   144
   169
   196
   225
   256
   289
   324
   361
   400
   441
   484
   529
   576
   625
   676
   729
   784
   841
   900



### 4. สร้างเมทริกซ์

$$A=\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 10\\
\end{bmatrix}$$

4.1 จงสร้า่ง Matrix B ด้วย square root ของ A นั้นคือ $B^2 = A$ <br>

In [17]:
A4 = [1:8 10];
A4 = reshape(A4, [3, 3])' # reshape คือ การเปลี่ยนมิติของ Matrix ไปเป็นในแบบที่เราต้องการ 
B = sqrt(A4)

A4 =

    1    2    3
    4    5    6
    7    8   10

B =

   1.0000   1.4142   1.7321
   2.0000   2.2361   2.4495
   2.6458   2.8284   3.1623



4.2 แทนสมาชิกในแนวทแยงมุมของ Matrix A ด้วย 1

In [18]:
modify_A = A4 - diag(diag(A4)) + eye(3)

modify_A =

   1   2   3
   4   1   6
   7   8   1



### 5. กำหนดให้

$$A=\begin{bmatrix}
5 & 8 & 7 \\
4 & 2 & 6 \\
9 & 8 & 9\\
\end{bmatrix}\hspace{10mm}
B=\begin{bmatrix}
-1 & 2 & -3 \\
2 & -4 & 5 \\
2 & 3 & 1\\
\end{bmatrix}\hspace{10mm}
C=\begin{bmatrix}
3 & 1 & 2 \\
-1 & 2 & 1 \\
-2 & -1 & 1\\
\end{bmatrix}$$
<br>
$$\hspace{10mm}
D=\begin{bmatrix}
1 & 2 & 3
\end{bmatrix}\hspace{10mm}
E=\begin{bmatrix}
-2\\
0\\
-2\\
\end{bmatrix}$$

In [36]:
A5 = [5 8 7; 4 2 6; 9 8 9]
B5 = [-1 2 -3; 2 -4 5; 2 3 1]
C5 = [3 1 2; -1 2 1; -2 -1 1]
D5 = [1 2 3]
E5 = [-2; 0; -2]

A5 =

   5   8   7
   4   2   6
   9   8   9

B5 =

  -1   2  -3
   2  -4   5
   2   3   1

C5 =

   3   1   2
  -1   2   1
  -2  -1   1

D5 =

   1   2   3

E5 =

  -2
   0
  -2



#### a) A+B-C

In [21]:
result_a = A5+B5+C5

result_a =

    7   11    6
    5    0   12
    9   10   11



#### b) A*B+B*C

In [23]:
result_b = A5*B5 + B5*C5

result_b =

   26    5   29
   12    7    9
   26   20   30



#### c) (A+B)\C

In [29]:
result_c = (A5+B5)\C5

result_c =

  -1.51508  -0.93216  -0.55276
   0.57035   0.18342   0.24623
   0.83920   0.72362   0.43719



#### d) (A+B)/C

In [30]:
result_d = (A5+B5)/C5

result_d =

   1.2222   3.4444  -1.8889
   4.1667  -1.1667   3.8333
   4.0000   3.0000  -1.0000



#### e) (A+B)*C

In [32]:
result_e = (A5+B5)*C5

result_e =

   -6   20   22
   -2   -9   21
    2   23   43



#### f) D*E

In [37]:
result_f = D5*E5

result_f = -8


#### g) A*E*D*C

In [38]:
result_g = A5*E5*D5*C5

result_g =

   120   -48  -168
   100   -40  -140
   180   -72  -252



### 6. กำหนดให้
$$A=\begin{bmatrix}1 & 2\\ 3 & 4\\
\end{bmatrix}\hspace{10mm}
B=\begin{bmatrix}-1 & 2\\ -2 & 3\\
\end{bmatrix}\hspace{10mm}$$

จงคำนวนหาค่าต่อไปนี้

In [40]:
A6 = reshape(1:4, [2,2])
B6 = [-1 2; -2 3]

A6 =

   1   3
   2   4

B6 =

  -1   2
  -2   3



a) 2^A

In [42]:
2^A6

ans =

   10.483   21.228
   14.152   31.711



b) A.^2

In [43]:
A6.^2

ans =

    1    9
    4   16



c) A.*B

In [45]:
A6.*B6

ans =

   -1    6
   -4   12



d) A.\B

In [47]:
A6.\B6

ans =

  -1.00000   0.66667
  -1.00000   0.75000



e) A./B

In [48]:
A6./B6

ans =

  -1.0000   1.5000
  -1.0000   1.3333



### 7. จงหารากของพหุนามต่อไปนี้

<img src="./images/problem10.png" />

In [54]:
# 7.1
p1 = [1 2 5];
p1_roots = roots(p1)

# 7.2
p2 = [1 -6 11 6];
p2_roots = roots(p2)

# 7.3
p3 = [ 1 0 -14 0 49 0 -36 0];
p3_roots = roots(p3)

# 7.4
p4 = [1 2 3 -26 -2 +72 -104 0];
p4_roots = roots(p4)

p1_roots =

  -1 + 2i
  -1 - 2i

p2_roots =

   3.21742 + 1.85643i
   3.21742 - 1.85643i
  -0.43484 + 0.00000i

p3_roots =

  -3.00000
   3.00000
  -2.00000
  -1.00000
   2.00000
   1.00000
   0.00000

p4_roots =

  -2.00000 + 3.00000i
  -2.00000 - 3.00000i
  -2.00000 + 0.00000i
   2.00000 + 0.00000i
   1.00000 + 1.00000i
   1.00000 - 1.00000i
   0.00000 + 0.00000i



### 8. จงแก้ระบบสมการหาค่าตัวแปรทั้งหมด
<img src="./images/problem11.png" />

In [56]:
# 8.1
A81 = [1 1; 2 -1];
B81 = [5; 1];
linsolve(A81, B81)

ans =

   2
   3



In [58]:
# 8.2 solved by inverse matrix
A82 = [2 -3; -3 2];
B82 = [-5; 1];
inv(A82)*B82

ans =

   1.4000
   2.6000



In [61]:
# 8.3 declared column matrix by transpose
A83 = [1 1 1; 1 -2 1; 3 1 -1];
B83 = [6 0 -1]';
linsolve(A83, B83)

ans =

   0.25000
   2.00000
   3.75000



In [63]:
# 8.4
A84 = [2 -2 1; -1 1 -1; -2 1 -1];
B84 = [1 -2 -6]';
linsolve(A84, B84)

ans =

   4
   5
   3

